apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:v1
          envFrom:
            - configMapRef:
                name: wordpress-configmap  # Reference to the ConfigMap
          ports:
            - containerPort: 80
              protocol: TCP

