# Use the official WordPress image from Docker Hub
FROM wordpress:latest

# Set environment variables for WordPress
ENV WORDPRESS_DB_HOST=mariadb-service.mariadb.svc.cluster.local
ENV WORDPRESS_DB_USER=wordpress
ENV WORDPRESS_DB_PASSWORD=wordpresspass
ENV WORDPRESS_DB_NAME=wordpressdb

# Expose port 80 internally within the cluster
EXPOSE 80

