# Use the official MariaDB image from Docker Hub
FROM mariadb:latest

# Set environment variables for MariaDB
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=wordpressdb
ENV MYSQL_USER=wordpress
ENV MYSQL_PASSWORD=wordpresspass

# Expose port 3306 (internal to the cluster)
EXPOSE 3306

