apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: mariadb
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk
  mysql-database: d29yZHByZXNzZGI=
  mysql-user: d29yZHByZXNz
  mysql-password: d29yZHByZXNzcGFzcw==

